server:
  port: 8082
#words: 我是中国人

# 集成eureka注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka
  instance:
    # 定义服务续约任务的调用间隔时间，默认为30秒
    lease-renewal-interval-in-seconds: 30
    # 定义服务失效的时间，默认为90秒
    lease-expiration-duration-in-seconds: 90


