spring:
  application:
    name: testspringcloud-eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
    #如果不想使用主机名来定义注册中心的地址，也可以使用IP地址的形式，但是需要增加下面的配置参数：
#    prefer-ip-address: true
  client:
    #默认情况下，eureka-server服务也会将自已作为客户端来尝试注册自已，
    #所以我们要禁用它的客户端注册行为。设置为false，代表不向注册中心注册自已。
    register-with-eureka: false
    #由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以设置为false。
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/