spring:
  application:
    name: testspringcloud-zipkin-sleuth
server:
  port: 8080
rabbitmq:
  host: localhost
  port: 5672
  username: full_access
  password: s3crEt
  virtual-host: /
zipkin:
  base-url: http://localhost:9411/  # zipkin服务器的地址
  enabled: true
  locator:
    discovery:
      enabled: false # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
  sender:
    type: rabbit
  #type: web # 设置使用http的方式传输数据
  service:
    name: ${spring.application.name}@${spring.cloud.client.ip-address}:${server.port}
sleuth:
  sampler:
    probability: 1.0