spring:
  application:
    name: springcloud-api-gateway
server:
  port: 5000
zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      url: http://localhost:8080/
    api-a:
      path: /api-a/**
      serviceId: testspringcloud-web
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/