spring:
  application:
    name: springcloud-api-gateway
server:
  port: 5000
zuul:
# yaml文件里面 * 号要加''(引号)，不然报错
#  ignored-services: '*'
#  routes:
# 单实例配置
#    api-a:
#      path: /api-a/**
#      url: http://localhost:8081/
#    testspringcloud-web: /api-a/**

#    api-a:
#      path: /api-a/**
#      serviceId: testspringcloud-web
#    api-b:
#      path: /api-b/**
#      serviceId: feign-consumer
#    api-c:
#      path: /api-c/**
#      serviceId: springcloud-api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/